import { describe, expect, it } from "vitest";
import { normalizeDraftPrBody, normalizeDraftPrTitle } from "./pr-conventions.js";

describe("pr conventions", () => {
  it("prefixes draft PR titles with [AI]", () => {
    expect(normalizeDraftPrTitle("Add checkout canary")).toBe("[AI] Add checkout canary");
    expect(normalizeDraftPrTitle("[ai] Add checkout canary")).toBe("[AI] Add checkout canary");
    expect(normalizeDraftPrTitle("")).toBe("[AI] Flux update");
  });

  it("adds Flux attribution section once", () => {
    const first = normalizeDraftPrBody("Implements checkout canary.");
    expect(first).toContain("## Generated by Flux");
    expect(first).toContain("Implements checkout canary.");

    const second = normalizeDraftPrBody(first);
    expect(second).toBe(first);
  });
});
