function collapseWhitespace(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

export function normalizeDraftPrTitle(title: string): string {
  const trimmed = collapseWhitespace(title);
  if (!trimmed) return "[AI] Flux update";
  if (/^\[ai\]\s*/i.test(trimmed)) {
    return trimmed.replace(/^\[ai\]\s*/i, "[AI] ");
  }
  return `[AI] ${trimmed}`;
}

export function normalizeDraftPrBody(body: string): string {
  const trimmed = body.trim();
  const attributionHeader = "## Generated by Flux";
  if (trimmed.toLowerCase().includes(attributionHeader.toLowerCase())) {
    return trimmed;
  }
  const attributionBlock = [
    attributionHeader,
    "",
    "- This draft PR was generated by Flux automation.",
  ].join("\n");
  if (!trimmed) {
    return attributionBlock;
  }
  return `${trimmed}\n\n${attributionBlock}`;
}
